project:
  type: website
  output-dir: docs

engine: knitr

website:
  title: "Molecular Data Analysis"
  bread-crumbs: false
  page-navigation: true
  navbar:
    background: primary
    search: true
    left:
      - text: "Setup and introduction to command line"
        file: part0-setup/index.qmd
      - text: "Part 1: Data visualization in R"
        file: part1-dataviz/index.qmd
      - text: "Part 2: RNA-seq analysis"
        file: part2-rna-seq/index.qmd
      - text: "Part 3: Genome assembly"
        file: part3-genome-assembly/index.qmd
  
  sidebar:
    - id: part0
      title: "Setup"
      style: "docked"
      collapse-level: 0
      contents:
        - part0-setup/index.qmd
        - section: "Episodes"
          contents: part0-setup/*.qmd
    
    - id: part1
      title: "Part 1: Data Viz in R"
      style: "docked"
      collapse-level: 0
      contents:
        - part1-dataviz/index.qmd
        - section: "Episodes"
          contents: part1-dataviz/*.qmd
    
    - id: part2
      title: "Part 2: RNA-seq analysis"
      style: "docked"
      collapse-level: 0
      contents:
        - part2-rna-seq/index.qmd
        - section: "Episodes"
          contents: part2-rna-seq/*.qmd
    
    - id: part3
      title: "Part 3: Genome assembly"
      style: "docked"
      collapse-level: 0
      contents:
        - part3-genome-assembly/index.qmd
        - section: "Episodes"
          contents: part3-genome-assembly/*.qmd

format:
  html:
    from: markdown+emoji
    theme: flatly
    css: /styles.css
    toc: true
    toc-depth: 3
