---
title: "Molecular Data Analysis & Bioinformatics"
subtitle: "Module of Quantitative Skills (MSc Biological Sciences)"
---

This module is designed to equip you with essential computational skills for modern biological research, from data visualization to advanced genomics analyses. Throughout this module, you'll work with real-world datasets and well-known bioinformatics tools, to build a strong foundation in reproducible computational biology.

## Learning objectives

By the end of this module, you will be able to:

- Create publication-quality data visualizations using R packages
- Perform RNA-seq analysis, from mapping raw reads to differential expression analysis
- Integrate RNA-seq results into a research project with a biological question
- Perform a genome assembly, and assess the quality of the resulting assembly
- Document and communicate your analyses effectively

## A note on genAI

Generative AI can be a useful tool to help you build bioinformatics pipelines. We think genAI is most useful when you already have a level of knowledge of a specific topic. Therefore, we strongly advice you to not use genAI to write all your code if you want to become a proficient bioinformatician. Use your time during this module to get to this level by writing code yourself or with help of the teachers. This gives you a solid basis and you will be able to assess whether AI-generated code makes sense, or is bloated with unnecessary parts, or is just plain wrong – the latter two are a common occurence! Later during your career, genAI can help you write better code faster.

In addition, we as teachers care about you learning bioinformatics, and not about receiving flawless and smooth assignments. We do not want to spend time reading and providing feedback on something that a machine wrote. These notes bring us to the following rules for this module:

- You **are** allowed to use genAI tools to support your learning and understanding of the course materials. For example, ask AI to re-explain a concept in a different way, or ask AI to ask you probing questions to increase your understandig

- You **are not** allowed to use genAI tools to replace your learning and critical thinking. Especially, you are not allowed to generate full solutions to assignments. 

## Module structure

This module is organized into four parts taught by Misha Paauw and Tijs Bliek, for which you can find the materials on this website. These materials are delivered in a **participatory live coding** style. That means that the instructor will type code, while sharing the screen, and that the students type along to repeat the code. This is highly effective, evidence-based way of teaching coding skills. The four parts are:

- **Part 0: Setup**: You'll configure your computational environment. In addition, you will learn the basics of working in a command-line environment.
- **Part 1: Data visualization in R**: What makes a data visualisation *good*, and how do we make them? We will explore these concepts using `ggplot2` in `R`. In addition, we will work on making our science reproducible using Github.
- **Part 2: RNA-seq analysis**: Explore RNA-seq datasets, from read mapping to differential gene expression analysis.
- **Part 3: Genome assembly**: Take on the challenge of reconstructing a genome from sequencing reads.

Then, Aalt-Jan van Dijk takes over for lectures and tutorials on **single-cell transcriptomics** and **gene-regulatory networks**. Teaching materials for these tutorials are distributed via Canvas.

## Timetable

This is the timetable of the module. It should correspond to your Datanose schedule, if not, Datanose is always the leading source of information!

### Week 1:
| Date | Time | Location | Type | Topic |
|--|---|---|---|---------|
| 28 sept | 13:00 - 14:00 | SP A1.24 | Lecture | Module introduction |
| 28 sept | 14:00 - 17:00 | SP A1.24  | Tutorial | Introductionto command line |
| 29 sept | 13:00 - 14:00 | SP B0.204 | Lecture | Principles of data visualization |
| 29 sept | 14:00 - 17:00 | SP B0.204 | Tutorial | Part 1: Data visualization in R (including mini presentation)|
| 30 sept | 13:00 - 14:00 | SP B0.201 | Lecture | RNA-seq lecture |
| 30 sept | 14:00 - 17:00 | SP B0.201 | Tutorial | Part 2: RNA-seq analysis (mapping reads) |

### Week 2:
| Date | Time | Location | Type | Topic |
|--|---|---|---|---------|
| 5 oct | 13:00 - 17:00 | SP A1.18 | Tutorial | Part 2: RNA-seq analysis (differential expression analysis)|
| 6 oct | 13:00 - 17:00 | SP B0.204 | :exclamation:*Assignment*:exclamation: | Part 2: Assignment RNA-seq |
| 8 oct | 13:00 - 15:00 | SP B0.208 | Lecture | Genome assembly & comparative genomics lecture |

### Week 3:
| Date | Time | Location | Type | Topic |
|--|---|---|---|---------|
| 12 oct | 13:00 - 17:00 | SP A1.24 | Tutorial | Part 3: Genome assembly & comparative genomics |
| 13 oct | 13:00 - 15:00 | SP A1.12 | Lecture | Single-cell omics lecture (Aalt-Jan) |
| 13 oct | 13:00 - 17:00 | SP A1.12 | Tutorial | Single-cell omics tutorial |
| 15 oct | 13:00 - 15:00 | SP G0.10 | Lecture | Lecture (Aalt-Jan) |
| 15 oct | 13:00 - 17:00 | SP G0.10 | Tutorial | Single-cell omics tutorial |

### Week 4:
| Date | Time | Location | Type | Topic |
|--|---|---|---|---------|
| 19 oct | 13:00 - 15:00 | SP A1.24 | Lecture | Gene regulatory networks lecture (Aalt-Jan) |
| 19 oct | 15:00 - 17:00 | SP A1.24 | Tutorial | Gene regulatory networks tutorial |
| 20 oct | 13:00 - 17:00 | SP A1.12 | :exclamation:*Assignment*:exclamation: | Gene regulatory networks assignment |


## Prerequisites

- Basic understanding of molecular biology concepts
- Basic programming experience in R
- Enthusiasm for learning computational approaches to biology!

## Getting started

Ready to begin? Head to the [Setup](part0-setup/index.qmd) section to prepare your computational environment.

