---
title: "Welcome"
sidebar: part1
---

Welcome to the data visualisation and reproducible science tutorial!

::: {.callout-note}
## Learning goals:

After this lesson, you should be able to:

With regard to reproducibility:

- Explain the FAIR principles and their relevance to data management in the biological sciences.
- Apply version control to a small data analysis project using `git`.
- Communicate analysis results to collaborations via `Github`.

With regard to data visualization:

- Design data visualizations that follow principles of visual clarity (e.g. data-to-ink ratio).
- Critically evaluate data visualizations and propose improvements.

:::

There will be two lessons in this tutorial:

## Reproducible science using GitHub:

Here, we will introduce the FAIR principle and the GitHub website. There's some preparation for you to do before this tutorial:

::: {.callout-note}
**Do this before the tutorial starts!**

You will need a GitHub account with 2 factor authentication setup.

1. Go to github.com → Sign up → follow the prompts
2. Make sure to set up 2 factor authentication using `Microsoft Authenticator`, `Google Authenticator`, SMS, or other options.
:::

## Data visualization in R

In this part of the tutorial you'll some important data visualisation principles, and apply them directly to a dataset in `R`. As a small (not graded) assignment, you'll make a data visualisation that's is terrible, and you'll present this visualisation to the rest of the group.
