---
title: "Welcome"
sidebar: part2
---

Welcome to the RNA-seq tutorial!

::: {.callout-note}
## Learning goals:

After this lesson, you should be able to:

- Design a RNA-seq experiment with enough statistical power
- Recognize common bioinformatics filetypes (`.fastq`, `.fasta`, `.bam`)
- Process RNA-seq data using appropriate tools, from raw reads to count table
- Interpret PCA and clustering results to asess whether sample groupingds alsign with the experimental design
- Apply DESeq2 to obtain lists of differentially expressed genes between two conditions
- Apply gene enrichment tests to defined gene lists
- Be able to create key plots such as volcano plots and heat maps
- Integrate RNA-seq results into a hypothesis about a biological problem

:::

For RNA-seq, there will be a 1-hour lecture and two tutorial sessions. In addition, there will be a 4-hour assignment session which will be graded.

## Mapping reads tutorial

In this tutorial, you will learn the command-line steps of an RNA-seq workflow. Briefly, you'll take the raw reads, perform quality control, trim low-quality sequences, map them to a genome, and then count how many reads 'landed' in each gene.

## Differential gene expression tutorial

In this tutorial, you will work with the 'count table' to discover genes that are up- or down-regulated in certain conditions. This tutorial will be performed in RStudio.

## Assignment

In the assignment, you will get a new count table, along with an R Markdown file containing code blocks to fill in and questions to answer. You hand in the file on Canvas, this will be graded.
