---
title: "Welcome"
sidebar: part3
---

Welcome to the genome assembly tutorial!

::: {.callout-note}
## Learning goals:

After this lesson, you should be able to:

- Explain how read length and sequencing depth affect assembly quality
- Execute a genome assembly, using command-line tools
- Select appropriate metrics for assessing genome assembly quality
- Interpret assembly quality metrics to identify potential issues with a genome assembly
- Justify the choice of sequencing technology for a genome assembly experiment
:::

You're going to assemble a genome! The genome will be from a bacterium, and you will discover which species it in the second part of today's tutorial, by doing a  phylogenetic analysis.

In this tutorial, you will be working more independently than before. Rather than participatory live coding, like we did in the previous tutorials, you will work on your own or together with your neighbour. The teachers are there to assist whenever you're stuck, or if you have curiosity questions!

There will be a mini assignment during this tutorial. You will create a figure highlighting the difference between different sequencing technologies for genome assembly. You'll briefly explain your figure to the teacher. This assignment will not be graded, but you need to `pass` this assignment. To pass, you need to show that you understand your figure and can clearly explain the main patterns you observe, including the effects of sequencing technology and sequencing depth. If your explanation is unclear or incomplete, we will give you feedback and ask you to continue working on your plot. You can then try the explanation again.

Let's start by going to the next episode!
